name: Build

on: [ push, pull_request ]

jobs:
  build_macos_310_311:
    name: MacOS 310,311 x86_64,arm64
    strategy:
      matrix:
        python_version: [ "cp310", "cp311" ]
        arch_cibw_go:
          - [ "x86_64", "amd64" ]
          - [ "arm64", "arm64" ]
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3

      - name: copy setup.py
        run: cp setup_ci.py setup.py

      - name: set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19.x"

      - name: install gopy
        run: go install github.com/go-python/gopy@v0.4.5

      - name: install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest

      - name: install python 3.10
        if: matrix.python_version == 'cp310'
        run: |
          curl -o python.pkg https://www.python.org/ftp/python/3.10.8/python-3.10.8-macos11.pkg
          sudo installer -pkg python.pkg -target /
          ln -s /usr/local/opt/python@3.10/bin/python3.10 /usr/local/bin/python_for_build

      - name: install python 3.11
        if: matrix.python_version == 'cp311'
        run: |
          curl -o python.pkg https://www.python.org/ftp/python/3.11.0/python-3.11.0-macos11.pkg
          sudo installer -pkg python.pkg -target /
          ln -s /usr/local/opt/python@3.11/bin/python3.11 /usr/local/bin/python_for_build

      - name: install cibuildwheel and pybindgen
        run: /usr/local/bin/python_for_build -m pip install cibuildwheel==2.11.2 pybindgen

      - name: build wheels
        run: /usr/local/bin/python_for_build -m cibuildwheel --output-dir wheelhouse
        env:
          CGO_ENABLED: 1
          CIBW_ARCHS: ${{ matrix.arch_cibw_go[0] }}
          GOARCH: ${{ matrix.arch_cibw_go[1] }}
          PYTHON_BINARY_PATH: /usr/local/bin/python_for_build
          CIBW_ENVIRONMENT: >
            PATH=$PATH:/usr/local/go/bin
          CIBW_BUILD: "${{ matrix.python_version }}-*"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./wheelhouse/*.whl


  build_macos_38_39_x86_64:
    name: MacOS 38,39 x86_64
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v3

      - name: copy setup.py
        run: cp setup_ci.py setup.py

      - name: set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19.x"

      - name: install gopy
        run: go install github.com/go-python/gopy@v0.4.5

      - name: install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.11.2
        env:
          CIBW_BUILD: "cp38-macosx_x86_64 cp39-macosx_x86_64"
          CIBW_ARCHS: "native"
          CIBW_ENVIRONMENT: >
            PATH=$PATH:/usr/local/go/bin
            GOARCH=amd64
          CIBW_BEFORE_ALL_MACOS: |
            curl -o python.pkg https://www.python.org/ftp/python/3.9.12/python-3.9.12-macosx10.9.pkg
            sudo installer -pkg python.pkg -target /

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./wheelhouse/*.whl


  build_linux:
    name: Linux 38,39,310,311 x86_64
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: copy setup.py
        run: cp setup_ci.py setup.py

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.11.2
        env:
          CIBW_BUILD: "cp3*_x86_64"
          CIBW_SKIP: "cp36-* cp37-* *-musllinux_x86_64"
          CIBW_ARCHS: "native"
          CIBW_ENVIRONMENT: >
            PATH=$PATH:/usr/local/go/bin
          CIBW_BEFORE_ALL_LINUX: |
            curl -o go.tar.gz https://dl.google.com/go/go1.19.3.linux-amd64.tar.gz
            tar -C /usr/local -xzf go.tar.gz
            go install github.com/go-python/gopy@v0.4.5
            go install golang.org/x/tools/cmd/goimports@latest

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./wheelhouse/*.whl
